apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesis-app
  namespace: tesis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tesis-app
  template:
    metadata:
      labels:
        app: tesis-app
    spec:
      imagePullSecrets:
      - name: ocir-secret
      containers:
      - name: tesis-app
        image: scl.ocir.io/axdkgb7ur2sa/tesis-app:latest
        ports:
        - containerPort: 80