apiVersion: v1
kind: Service
metadata:
  name: tesis-app-service
  namespace: tesis
spec:
  type: LoadBalancer
  selector:
    app: tesis-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80