name: CI-CD-OKE

on:
  push:
    branches:
      - gitops

env:
  REGION: scl
  NAMESPACE: axdkgb7ur2sa
  REPO_NAME: tesis-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to OCIR
      env:
        OCIR_PASSWORD: ${{ secrets.OCIR_PASSWORD }}
        OCIR_USERNAME: ${{ secrets.OCIR_USERNAME }}
      run: |
        echo "$OCIR_PASSWORD" | docker login $REGION.ocir.io \
        -u "$OCIR_USERNAME" --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: ${{ env.REGION }}.ocir.io/${{ env.NAMESPACE }}/${{ env.REPO_NAME }}:latest
