name: CI-CD-OKE

on:
  push:
    branches:
      - main

env:
  REGION: sa-santiago-1
  NAMESPACE: axdkgb7ur2sa
  REPO_NAME: tesis-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to OCIR
      run: |
        echo "${{ secrets.OCIR_PASSWORD }}" | docker login $REGION.ocir.io \
        -u "${{ secrets.OCIR_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t $REGION.ocir.io/$NAMESPACE/$REPO_NAME:latest .

    - name: Push image to OCIR
      run: |
        docker push $REGION.ocir.io/$NAMESPACE/$REPO_NAME:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl get nodes

    - name: Deploy to OKE
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml